# Generated by Django 6.1 on 2026-08-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GITHUB', 'GitHub'), ('GITLAB', 'GitLab')], default='GITHUB', max_length=20)),
                ('owner', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField(max_length=500)),
                ('webhook_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='git_repository', to='projects.project')),
            ],
        ),
    ]
